apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-sample
spec:
  parallelism: 1
  script:
    configMap:
      name: test-scripts
      file: archive.tar
  separate: false
  arguments: --summary-mode=full
  runner:
    env:
      - name: K6_OUT
        value: experimental-prometheus-rw
      - name: BASE_URL
        value: 18.153.7.27
    envFrom:
     - configMapRef:
         name: prometheus-config
    resources:
      limits:
        cpu: 200m
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 500Mi